require:
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  NewCops: enable

#
# Gemspec
#

Gemspec/DuplicatedAssignment:
  Enabled: false

#
# Layout
#

Layout/LineLength:
  Max: 128

#
# Lint
#

Lint/SuppressedException:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

#
# Metrics
#

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

#
# Naming
#

Naming/RescuedExceptionsVariableName:
  Enabled: false

#
# Style
#

Style/StringLiterals:
  EnforcedStyle: double_quotes
