language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.16.1
  - bundle --version

bundler_args: --without development

rvm:
  - jruby-9.1.15.0
  - 2
  - 2.1
  - 2.2
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - truffleruby
matrix:
  allow_failures:
    - rvm: truffleruby
  fast_finish: true

branches:
  only:
    - master
