name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2
          - ruby-3.3
          - ruby-3.4
          - ruby-4.0
          - jruby-9.4.12
          - jruby-10.0.0
          - truffleruby
        os: [ubuntu-latest, windows-latest]
        exclude:
          - { ruby: truffleruby, os: windows-latest }
          - { ruby: jruby-10.0.0, os: windows-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake compile spec

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler: 2.5.23
          bundler-cache: true

      - run: bundle exec rake rubocop
